application: cwilsotest-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /blog
  static_dir: blog

- url: /tests
  static_dir: tests
  
- url: /
  static_dir: assets
